# serverless.yml

service: job-server

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: '/getjobdetails'
          method: GET
          cors: true
      - http:
          path: '/getjobdetailsbyname'
          method: GET
          cors: true
          request:
            template:
              application/json: '{ "name": "$input.params(''name'')" }'
      - http:
          path: '/deletejobdetails'
          method: DELETE
          cors: true
      - http:
          path: '/createjobdetails'
          method: POST
          cors: true
      - http:
          path: '/updatejobdetail'
          method: POST
          cors: true
          request:
            template:
              application/json: '{ "id": "$input.params(''id'')" }'

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
